import RouteLayout from "./routeLayout";



export const metadata = {
  title: "Ecommerce ",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <RouteLayout>{children}</RouteLayout>;
}
